### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by magicalbanana** [autonomy/alterant#1]
Can you provide an example repo on how this is utilized?

**Comment by jseadragon** [comment]
+1, that would be useful. I read through the readme, and it's not clear to me how the .yml relates to manging dotfiles

**Comment by andrewrynhard** [comment]
@magicalbanana @jseadragon: an example can be found here
https://github.com/andrewrynhard/dotfiles

I agree the documentation needs to be improved. Keep in mind this is an alpha build and I am in the process of changing some things. When the changes come I will be sure to provide better documentation
